/**
 * Node server: the exact Worker app, served by Node.
 *
 * Serves three roles with the same code:
 *  - local development (`npm run dev`, loopback-only, random generated secrets)
 *  - tests / E2E (isolated temp DB via DEV_DB_DIR)
 *  - self-hosted production on any server (secrets via env vars, DATA_DIR
 *    for the SQLite file, optional HOST=0.0.0.0 behind your own proxy)
 *
 * Cloudflare production deploys the same app via `wrangler deploy` instead.
 */
import { existsSync, mkdirSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { serve } from "@hono/node-server";
import { encryptString } from "./core/crypto";
import app from "./index";
import { createAssetsHandler } from "./node/assets";
import { NodeSqliteD1 } from "./node/d1-sqlite";

const here = dirname(fileURLToPath(import.meta.url));
const workerRoot = join(here, "..");

// ---------------------------------------------------------------------------
// Secrets: environment variables first (self-hosted), .dev-vars.json fallback
// (generated by `npm run dev` for local development).
// ---------------------------------------------------------------------------

let masterKey: string | undefined = process.env.MASTER_KEY;
let jwtSecret: string | undefined = process.env.JWT_SECRET;
let bootstrapToken: string | undefined = process.env.BOOTSTRAP_TOKEN;

const varsFile = join(workerRoot, ".dev-vars.json");
if ((!masterKey || !jwtSecret) && existsSync(varsFile)) {
  const devVars = JSON.parse(readFileSync(varsFile, "utf8")) as {
    master_key: string;
    jwt_secret: string;
    bootstrap_token?: string;
  };
  masterKey ??= devVars.master_key;
  jwtSecret ??= devVars.jwt_secret;
  bootstrapToken ??= devVars.bootstrap_token;
}

if (!masterKey || !jwtSecret) {
  console.error(
    "❌ Faltan secretos: define MASTER_KEY y JWT_SECRET (variables de entorno) o ejecuta `npm run dev` una vez para generar .dev-vars.json.",
  );
  process.exit(1);
}

// ---------------------------------------------------------------------------
// Database: apply migrations, optionally seed demo agents
// ---------------------------------------------------------------------------

const dataDir = process.env.DEV_DB_DIR ?? process.env.DATA_DIR ?? join(workerRoot, ".dev");
const dbFile = join(dataDir, "consenso.sqlite");
mkdirSync(dirname(dbFile), { recursive: true });
const db = new NodeSqliteD1(dbFile);

const migrationsDir = join(workerRoot, "migrations");
const { readdirSync } = await import("node:fs");
const migrations = readdirSync(migrationsDir)
  .filter((f) => f.endsWith(".sql"))
  .sort();
for (const m of migrations) {
  await db.exec(readFileSync(join(migrationsDir, m), "utf8"));
}

if (process.env.SEED_DEMO === "1") {
  const n = await db.prepare("SELECT COUNT(*) AS n FROM agents").first<{ n: number }>();
  if ((n?.n ?? 0) === 0) {
    const demoUrl = process.env.DEMO_LLM_URL ?? "http://127.0.0.1:8790/v1/chat/completions";
    const demoAgents = [
      {
        key: "groq",
        name: "Agent_Groq",
        display_name: "Groq",
        role: "moderator",
        model: "demo-moderator",
      },
      {
        key: "openrouter",
        name: "Agent_OpenRouter",
        display_name: "OpenRouter",
        role: "participant",
        model: "demo-expert-a",
      },
      {
        key: "deepseek",
        name: "Agent_DeepSeek",
        display_name: "DeepSeek",
        role: "participant",
        model: "demo-expert-b",
      },
      {
        key: "mistral",
        name: "Agent_Mistral",
        display_name: "Mistral",
        role: "participant",
        model: "demo-expert-c",
      },
    ];
    for (const a of demoAgents) {
      const ct = await encryptString(masterKey, "demo-key-not-real");
      await db
        .prepare(
          `INSERT INTO agents (key, name, display_name, url, model, api_key_ciphertext, timeout_s, role, active)
           VALUES (?, ?, ?, ?, ?, ?, 20, ?, 1)`,
        )
        .bind(a.key, a.name, a.display_name, demoUrl, a.model, ct, a.role)
        .run();
    }
    console.log(`🌱 4 agentes demo insertados (URL mock: ${demoUrl})`);
  }
}

// ---------------------------------------------------------------------------
// Serve
// ---------------------------------------------------------------------------

// Same directory the production Worker serves (vite builds here directly).
const assets = createAssetsHandler(join(workerRoot, "public"));
const port = Number(process.env.PORT ?? 8787);
// HOST=0.0.0.0 for Docker/VPS (behind your own proxy + TLS). Default stays
// loopback so a bare `npm run dev` is never reachable from the network.
const host = process.env.HOST ?? "127.0.0.1";

const env = {
  DB: db,
  ASSETS: {
    fetch: (input: Request | string, init?: RequestInit) => assets(new Request(input, init)),
  },
  MASTER_KEY: masterKey,
  JWT_SECRET: jwtSecret,
  BOOTSTRAP_TOKEN: bootstrapToken,
  TRUST_PROXY_IP: process.env.TRUST_PROXY_IP,
};

const server = serve(
  { fetch: (req) => app.fetch(req, env as never), port, hostname: host },
  (info) => {
    console.log(
      `🚀 Consenso AI v2 (node) → http://${host === "0.0.0.0" ? "<todas-las-interfaces>" : host}:${info.port}`,
    );
    console.log(`   Datos: ${dbFile}`);
    if (host === "0.0.0.0") {
      console.log(
        "   ⚠️  Expuesto a la red — ponlo detrás de un proxy con TLS y usa TRUST_PROXY_IP=1.",
      );
    }
  },
);

server.addListener("error", (err: NodeJS.ErrnoException) => {
  if (err.code === "EADDRINUSE") {
    console.error(`❌ Puerto ${port} ocupado (¿ya hay un servidor corriendo?).`);
  } else {
    console.error("❌ Error del servidor:", err.message);
  }
  process.exit(1);
});

for (const sig of ["SIGINT", "SIGTERM"] as const) {
  process.on(sig, () => {
    server.close();
    process.exit(0);
  });
}
